services:
  postgres:
    image: postgres:15-alpine
    container_name: matefield_db_local
    environment:
      POSTGRES_USER: \
      POSTGRES_PASSWORD: \
      POSTGRES_DB: \
    ports:
      - "5432:5432"
    networks:
      - matefield_local_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U matefield_user -d matefield_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  mock_rcon:
    image: matefield_bot-mock_rcon
    container_name: mock_rcon
    ports:
      - "9001:7776"
    networks:
      - matefield_local_net

  api_rcon:
    image: matefield_bot-api_rcon
    container_name: api_rcon_local
    env_file:
      - .env.local
    command: sh -c "uv run alembic upgrade head && uv run uvicorn src.main:app --host 0.0.0.0 --port 8000"
    ports:
      - "8000:8000"
    volumes:
      - ./backups:/app/apps/api_rcon/backups
    networks:
      - matefield_local_net
    depends_on:
      postgres:
        condition: service_healthy
      mock_rcon:
        condition: service_started

  discord_bot:
    image: matefield_bot-discord_bot
    container_name: discord_bot_local
    env_file:
      - .env.local
    networks:
      - matefield_local_net
    depends_on:
      - api_rcon

networks:
  matefield_local_net:
    name: matefield_bot_matefield_local_net
