"""Add player fields

Revision ID: 7ea26e120206
Revises: 47312279a0c3
Create Date: 2026-09-14 16:03:53.027733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7ea26e120206'
down_revision: Union[str, Sequence[str], None] = '47312279a0c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('in_game_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('players', sa.Column('avatar_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'avatar_url')
    op.drop_column('players', 'in_game_name')
    # ### end Alembic commands ###
